### PR TITLE
Rollback body if inside an unloaded block & fix for autostep when autostepping in a corner

### PR DESCRIPTION
**Pull request by MCArth**
Hi, sorry for this addressing two things at once

Feel free to close this - and potentially address one or both of the issues with your own changes 

The first change: I add the option isBodyInsideUnloadedBlock which rolls back the body to before the changes made by the tick if the body is inside an unloaded block. There's an early out in the main noa tick if the player co-ordinates aren't located in a loaded chunk but this has a few drawbacks:
1. The body will end up 1 physics tick inside the unloaded chunk, and so will end up inside a block if one exists
2. It doesn't check the corners of the player
3. It does nothing for non-player bodies

This logic could have been implemented elsewhere but it felt cleanest here. Unsure how it would be called in noa - personally I'm checking the corners of the body for the local player and just the middle of the base for all other bodies.

The second change is the logic for `bail if no movement happened in the originally blocked direction`

Before the change, if a player walks into a corner and one of the "walls" is one block high and one is more than that, the player won't autostep the "wall" that is one block high. With this change, the player does.

### CODE REVIEW

**Comment by fenomas** [comment]
Hi, sorry for the late reply. I see what you mean about needing to prevent objects from  entering unloaded chunks, but I think it should be handled inside the main engine logic, rather than here - because this engine in principle doesn't know what chunks are or what it means for a block to be loaded or not, it's just meant to handle the interpolation.

With that said, in thinking about how best to solve this, it occurred to me that the simplest solution might be to just have the main engine treat unloaded blocks as being solid. That way any entity trying to move into an unloaded region would just bump into an invisible wall, which in principle shouldn't affect gameplay if it's happening "at the edge of the world" far from the player.

Can you think of any problems that would cause? The only think that occurs to me is that it would obviate the way entities in unloaded chunks currently fall off the world, meaning they eventually get culled, but that's not a very good mechanic anyway - it would probably be better for game clients to actively do something with entities like that (either because they do their own checking when chunks are unloaded, or because the engine dispatches an event for it.)

**Comment by MCArth** [comment]
That sounds like a cleaner approach

The main issue I see is players would lose their vertical momentum when falling onto the top of an unloaded chunk but this isn't a concern in most games (and would always be corrected by server side movement in multiplayer games regardless)

**Comment by fenomas** [comment]
That's a great point. I guess the engine should have an option on the physics behavior, and it might be worth considering emitting an event for entities that touch a chunk being removed. But OTOH a game could listen to `chunkBeingRemoved` and handle this itself, which might be better since there would be performance impact to having the engine do the checks....

**Comment by MCArth** [comment]
Indeed, makes sense - flexibility+perf is better if not all games want it

Feel free to close!

**Pull request closed without merging**
